<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::firstOrCreate( ['iso'=>'AF', 'name'=>'AFGHANISTAN', 'nicename'=>'Afghanistan', 'iso3'=>'AFG', 'numcode'=>4, 'phonecode'=>93, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AX', 'name'=>'ALAND ISLANDS', 'nicename'=>'Aland Islands', 'iso3'=>'ALA', 'numcode'=>248, 'phonecode'=>358, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AL', 'name'=>'ALBANIA', 'nicename'=>'Albania', 'iso3'=>'ALB', 'numcode'=>8, 'phonecode'=>355, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'DZ', 'name'=>'ALGERIA', 'nicename'=>'Algeria', 'iso3'=>'DZA', 'numcode'=>12, 'phonecode'=>213, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AS', 'name'=>'AMERICAN SAMOA', 'nicename'=>'American Samoa', 'iso3'=>'ASM', 'numcode'=>16, 'phonecode'=>1684, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AD', 'name'=>'ANDORRA', 'nicename'=>'Andorra', 'iso3'=>'AND', 'numcode'=>20, 'phonecode'=>376, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AO', 'name'=>'ANGOLA', 'nicename'=>'Angola', 'iso3'=>'AGO', 'numcode'=>24, 'phonecode'=>244, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AI', 'name'=>'ANGUILLA', 'nicename'=>'Anguilla', 'iso3'=>'AIA', 'numcode'=>660, 'phonecode'=>1264, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AQ', 'name'=>'ANTARCTICA', 'nicename'=>'Antarctica', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>0, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AG', 'name'=>'ANTIGUA AND BARBUDA', 'nicename'=>'Antigua and Barbuda', 'iso3'=>'ATG', 'numcode'=>28, 'phonecode'=>1268, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AR', 'name'=>'ARGENTINA', 'nicename'=>'Argentina', 'iso3'=>'ARG', 'numcode'=>32, 'phonecode'=>54, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AM', 'name'=>'ARMENIA', 'nicename'=>'Armenia', 'iso3'=>'ARM', 'numcode'=>51, 'phonecode'=>374, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AW', 'name'=>'ARUBA', 'nicename'=>'Aruba', 'iso3'=>'ABW', 'numcode'=>533, 'phonecode'=>297, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AP', 'name'=>'ASIA PACIFIC REGION', 'nicename'=>'Asia / Pacific Region', 'iso3'=>'0', 'numcode'=>0, 'phonecode'=>0, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AU', 'name'=>'AUSTRALIA', 'nicename'=>'Australia', 'iso3'=>'AUS', 'numcode'=>36, 'phonecode'=>61, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AT', 'name'=>'AUSTRIA', 'nicename'=>'Austria', 'iso3'=>'AUT', 'numcode'=>40, 'phonecode'=>43, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AZ', 'name'=>'AZERBAIJAN', 'nicename'=>'Azerbaijan', 'iso3'=>'AZE', 'numcode'=>31, 'phonecode'=>994, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BS', 'name'=>'BAHAMAS', 'nicename'=>'Bahamas', 'iso3'=>'BHS', 'numcode'=>44, 'phonecode'=>1242, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BH', 'name'=>'BAHRAIN', 'nicename'=>'Bahrain', 'iso3'=>'BHR', 'numcode'=>48, 'phonecode'=>973, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BD', 'name'=>'BANGLADESH', 'nicename'=>'Bangladesh', 'iso3'=>'BGD', 'numcode'=>50, 'phonecode'=>880, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BB', 'name'=>'BARBADOS', 'nicename'=>'Barbados', 'iso3'=>'BRB', 'numcode'=>52, 'phonecode'=>1246, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BY', 'name'=>'BELARUS', 'nicename'=>'Belarus', 'iso3'=>'BLR', 'numcode'=>112, 'phonecode'=>375, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BE', 'name'=>'BELGIUM', 'nicename'=>'Belgium', 'iso3'=>'BEL', 'numcode'=>56, 'phonecode'=>32, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BZ', 'name'=>'BELIZE', 'nicename'=>'Belize', 'iso3'=>'BLZ', 'numcode'=>84, 'phonecode'=>501, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BJ', 'name'=>'BENIN', 'nicename'=>'Benin', 'iso3'=>'BEN', 'numcode'=>204, 'phonecode'=>229, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BM', 'name'=>'BERMUDA', 'nicename'=>'Bermuda', 'iso3'=>'BMU', 'numcode'=>60, 'phonecode'=>1441, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BT', 'name'=>'BHUTAN', 'nicename'=>'Bhutan', 'iso3'=>'BTN', 'numcode'=>64, 'phonecode'=>975, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BO', 'name'=>'BOLIVIA', 'nicename'=>'Bolivia', 'iso3'=>'BOL', 'numcode'=>68, 'phonecode'=>591, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BQ', 'name'=>'BONAIRE, SINT EUSTATIUS AND SABA', 'nicename'=>'Bonaire, Sint Eustatius and Saba', 'iso3'=>'BES', 'numcode'=>535, 'phonecode'=>599, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BA', 'name'=>'BOSNIA AND HERZEGOVINA', 'nicename'=>'Bosnia and Herzegovina', 'iso3'=>'BIH', 'numcode'=>70, 'phonecode'=>387, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BW', 'name'=>'BOTSWANA', 'nicename'=>'Botswana', 'iso3'=>'BWA', 'numcode'=>72, 'phonecode'=>267, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BV', 'name'=>'BOUVET ISLAND', 'nicename'=>'Bouvet Island', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>0, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BR', 'name'=>'BRAZIL', 'nicename'=>'Brazil', 'iso3'=>'BRA', 'numcode'=>76, 'phonecode'=>55, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IO', 'name'=>'BRITISH INDIAN OCEAN TERRITORY', 'nicename'=>'British Indian Ocean Territory', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>246, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BN', 'name'=>'BRUNEI DARUSSALAM', 'nicename'=>'Brunei Darussalam', 'iso3'=>'BRN', 'numcode'=>96, 'phonecode'=>673, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BG', 'name'=>'BULGARIA', 'nicename'=>'Bulgaria', 'iso3'=>'BGR', 'numcode'=>100, 'phonecode'=>359, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BF', 'name'=>'BURKINA FASO', 'nicename'=>'Burkina Faso', 'iso3'=>'BFA', 'numcode'=>854, 'phonecode'=>226, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BI', 'name'=>'BURUNDI', 'nicename'=>'Burundi', 'iso3'=>'BDI', 'numcode'=>108, 'phonecode'=>257, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KH', 'name'=>'CAMBODIA', 'nicename'=>'Cambodia', 'iso3'=>'KHM', 'numcode'=>116, 'phonecode'=>855, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CM', 'name'=>'CAMEROON', 'nicename'=>'Cameroon', 'iso3'=>'CMR', 'numcode'=>120, 'phonecode'=>237, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CA', 'name'=>'CANADA', 'nicename'=>'Canada', 'iso3'=>'CAN', 'numcode'=>124, 'phonecode'=>1, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CV', 'name'=>'CAPE VERDE', 'nicename'=>'Cape Verde', 'iso3'=>'CPV', 'numcode'=>132, 'phonecode'=>238, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KY', 'name'=>'CAYMAN ISLANDS', 'nicename'=>'Cayman Islands', 'iso3'=>'CYM', 'numcode'=>136, 'phonecode'=>1345, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CF', 'name'=>'CENTRAL AFRICAN REPUBLIC', 'nicename'=>'Central African Republic', 'iso3'=>'CAF', 'numcode'=>140, 'phonecode'=>236, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TD', 'name'=>'CHAD', 'nicename'=>'Chad', 'iso3'=>'TCD', 'numcode'=>148, 'phonecode'=>235, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CL', 'name'=>'CHILE', 'nicename'=>'Chile', 'iso3'=>'CHL', 'numcode'=>152, 'phonecode'=>56, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CN', 'name'=>'CHINA', 'nicename'=>'China', 'iso3'=>'CHN', 'numcode'=>156, 'phonecode'=>86, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CX', 'name'=>'CHRISTMAS ISLAND', 'nicename'=>'Christmas Island', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>61, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CC', 'name'=>'COCOS (KEELING) ISLANDS', 'nicename'=>'Cocos (Keeling) Islands', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>672, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CO', 'name'=>'COLOMBIA', 'nicename'=>'Colombia', 'iso3'=>'COL', 'numcode'=>170, 'phonecode'=>57, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KM', 'name'=>'COMOROS', 'nicename'=>'Comoros', 'iso3'=>'COM', 'numcode'=>174, 'phonecode'=>269, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CG', 'name'=>'CONGO', 'nicename'=>'Congo', 'iso3'=>'COG', 'numcode'=>178, 'phonecode'=>242, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CD', 'name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'nicename'=>'Congo, the Democratic Republic of the', 'iso3'=>'COD', 'numcode'=>180, 'phonecode'=>242, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CK', 'name'=>'COOK ISLANDS', 'nicename'=>'Cook Islands', 'iso3'=>'COK', 'numcode'=>184, 'phonecode'=>682, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CR', 'name'=>'COSTA RICA', 'nicename'=>'Costa Rica', 'iso3'=>'CRI', 'numcode'=>188, 'phonecode'=>506, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CI', 'name'=>"COTE D'IVOIRE", 'nicename'=>"Cote D'Ivoire", 'iso3'=>'CIV', 'numcode'=>384, 'phonecode'=>225, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'HR', 'name'=>'CROATIA', 'nicename'=>'Croatia', 'iso3'=>'HRV', 'numcode'=>191, 'phonecode'=>385, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CU', 'name'=>'CUBA', 'nicename'=>'Cuba', 'iso3'=>'CUB', 'numcode'=>192, 'phonecode'=>53, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CW', 'name'=>'CURACAO', 'nicename'=>'Curacao', 'iso3'=>'CUW', 'numcode'=>531, 'phonecode'=>599, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CY', 'name'=>'CYPRUS', 'nicename'=>'Cyprus', 'iso3'=>'CYP', 'numcode'=>196, 'phonecode'=>357, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CZ', 'name'=>'CZECH REPUBLIC', 'nicename'=>'Czech Republic', 'iso3'=>'CZE', 'numcode'=>203, 'phonecode'=>420, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'DK', 'name'=>'DENMARK', 'nicename'=>'Denmark', 'iso3'=>'DNK', 'numcode'=>208, 'phonecode'=>45, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'DJ', 'name'=>'DJIBOUTI', 'nicename'=>'Djibouti', 'iso3'=>'DJI', 'numcode'=>262, 'phonecode'=>253, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'DM', 'name'=>'DOMINICA', 'nicename'=>'Dominica', 'iso3'=>'DMA', 'numcode'=>212, 'phonecode'=>1767, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'DO', 'name'=>'DOMINICAN REPUBLIC', 'nicename'=>'Dominican Republic', 'iso3'=>'DOM', 'numcode'=>214, 'phonecode'=>1809, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'EC', 'name'=>'ECUADOR', 'nicename'=>'Ecuador', 'iso3'=>'ECU', 'numcode'=>218, 'phonecode'=>593, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'EG', 'name'=>'EGYPT', 'nicename'=>'Egypt', 'iso3'=>'EGY', 'numcode'=>818, 'phonecode'=>20, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SV', 'name'=>'EL SALVADOR', 'nicename'=>'El Salvador', 'iso3'=>'SLV', 'numcode'=>222, 'phonecode'=>503, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GQ', 'name'=>'EQUATORIAL GUINEA', 'nicename'=>'Equatorial Guinea', 'iso3'=>'GNQ', 'numcode'=>226, 'phonecode'=>240, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ER', 'name'=>'ERITREA', 'nicename'=>'Eritrea', 'iso3'=>'ERI', 'numcode'=>232, 'phonecode'=>291, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'EE', 'name'=>'ESTONIA', 'nicename'=>'Estonia', 'iso3'=>'EST', 'numcode'=>233, 'phonecode'=>372, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ET', 'name'=>'ETHIOPIA', 'nicename'=>'Ethiopia', 'iso3'=>'ETH', 'numcode'=>231, 'phonecode'=>251, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'FK', 'name'=>'FALKLAND ISLANDS (MALVINAS)', 'nicename'=>'Falkland Islands (Malvinas)', 'iso3'=>'FLK', 'numcode'=>238, 'phonecode'=>500, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'FO', 'name'=>'FAROE ISLANDS', 'nicename'=>'Faroe Islands', 'iso3'=>'FRO', 'numcode'=>234, 'phonecode'=>298, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'FJ', 'name'=>'FIJI', 'nicename'=>'Fiji', 'iso3'=>'FJI', 'numcode'=>242, 'phonecode'=>679, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'FI', 'name'=>'FINLAND', 'nicename'=>'Finland', 'iso3'=>'FIN', 'numcode'=>246, 'phonecode'=>358, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'FR', 'name'=>'FRANCE', 'nicename'=>'France', 'iso3'=>'FRA', 'numcode'=>250, 'phonecode'=>33, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GF', 'name'=>'FRENCH GUIANA', 'nicename'=>'French Guiana', 'iso3'=>'GUF', 'numcode'=>254, 'phonecode'=>594, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PF', 'name'=>'FRENCH POLYNESIA', 'nicename'=>'French Polynesia', 'iso3'=>'PYF', 'numcode'=>258, 'phonecode'=>689, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TF', 'name'=>'FRENCH SOUTHERN TERRITORIES', 'nicename'=>'French Southern Territories', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>0, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GA', 'name'=>'GABON', 'nicename'=>'Gabon', 'iso3'=>'GAB', 'numcode'=>266, 'phonecode'=>241, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GM', 'name'=>'GAMBIA', 'nicename'=>'Gambia', 'iso3'=>'GMB', 'numcode'=>270, 'phonecode'=>220, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GE', 'name'=>'GEORGIA', 'nicename'=>'Georgia', 'iso3'=>'GEO', 'numcode'=>268, 'phonecode'=>995, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'DE', 'name'=>'GERMANY', 'nicename'=>'Germany', 'iso3'=>'DEU', 'numcode'=>276, 'phonecode'=>49, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GH', 'name'=>'GHANA', 'nicename'=>'Ghana', 'iso3'=>'GHA', 'numcode'=>288, 'phonecode'=>233, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GI', 'name'=>'GIBRALTAR', 'nicename'=>'Gibraltar', 'iso3'=>'GIB', 'numcode'=>292, 'phonecode'=>350, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GR', 'name'=>'GREECE', 'nicename'=>'Greece', 'iso3'=>'GRC', 'numcode'=>300, 'phonecode'=>30, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GL', 'name'=>'GREENLAND', 'nicename'=>'Greenland', 'iso3'=>'GRL', 'numcode'=>304, 'phonecode'=>299, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GD', 'name'=>'GRENADA', 'nicename'=>'Grenada', 'iso3'=>'GRD', 'numcode'=>308, 'phonecode'=>1473, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GP', 'name'=>'GUADELOUPE', 'nicename'=>'Guadeloupe', 'iso3'=>'GLP', 'numcode'=>312, 'phonecode'=>590, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GU', 'name'=>'GUAM', 'nicename'=>'Guam', 'iso3'=>'GUM', 'numcode'=>316, 'phonecode'=>1671, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GT', 'name'=>'GUATEMALA', 'nicename'=>'Guatemala', 'iso3'=>'GTM', 'numcode'=>320, 'phonecode'=>502, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GG', 'name'=>'GUERNSEY', 'nicename'=>'Guernsey', 'iso3'=>'GGY', 'numcode'=>831, 'phonecode'=>44, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GN', 'name'=>'GUINEA', 'nicename'=>'Guinea', 'iso3'=>'GIN', 'numcode'=>324, 'phonecode'=>224, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GW', 'name'=>'GUINEA-BISSAU', 'nicename'=>'Guinea-Bissau', 'iso3'=>'GNB', 'numcode'=>624, 'phonecode'=>245, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GY', 'name'=>'GUYANA', 'nicename'=>'Guyana', 'iso3'=>'GUY', 'numcode'=>328, 'phonecode'=>592, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'HT', 'name'=>'HAITI', 'nicename'=>'Haiti', 'iso3'=>'HTI', 'numcode'=>332, 'phonecode'=>509, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'HM', 'name'=>'HEARD ISLAND AND MCDONALD ISLANDS', 'nicename'=>'Heard Island and Mcdonald Islands', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>0, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'VA', 'name'=>'HOLY SEE (VATICAN CITY STATE)', 'nicename'=>'Holy See (Vatican City State)', 'iso3'=>'VAT', 'numcode'=>336, 'phonecode'=>39, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'HN', 'name'=>'HONDURAS', 'nicename'=>'Honduras', 'iso3'=>'HND', 'numcode'=>340, 'phonecode'=>504, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'HK', 'name'=>'HONG KONG', 'nicename'=>'Hong Kong', 'iso3'=>'HKG', 'numcode'=>344, 'phonecode'=>852, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'HU', 'name'=>'HUNGARY', 'nicename'=>'Hungary', 'iso3'=>'HUN', 'numcode'=>348, 'phonecode'=>36, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IS', 'name'=>'ICELAND', 'nicename'=>'Iceland', 'iso3'=>'ISL', 'numcode'=>352, 'phonecode'=>354, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IN', 'name'=>'INDIA', 'nicename'=>'India', 'iso3'=>'IND', 'numcode'=>356, 'phonecode'=>91, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ID', 'name'=>'INDONESIA', 'nicename'=>'Indonesia', 'iso3'=>'IDN', 'numcode'=>360, 'phonecode'=>62, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IR', 'name'=>'IRAN, ISLAMIC REPUBLIC OF', 'nicename'=>'Iran, Islamic Republic of', 'iso3'=>'IRN', 'numcode'=>364, 'phonecode'=>98, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IQ', 'name'=>'IRAQ', 'nicename'=>'Iraq', 'iso3'=>'IRQ', 'numcode'=>368, 'phonecode'=>964, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IE', 'name'=>'IRELAND', 'nicename'=>'Ireland', 'iso3'=>'IRL', 'numcode'=>372, 'phonecode'=>353, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IM', 'name'=>'ISLE OF MAN', 'nicename'=>'Isle of Man', 'iso3'=>'IMN', 'numcode'=>833, 'phonecode'=>44, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IL', 'name'=>'ISRAEL', 'nicename'=>'Israel', 'iso3'=>'ISR', 'numcode'=>376, 'phonecode'=>972, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'IT', 'name'=>'ITALY', 'nicename'=>'Italy', 'iso3'=>'ITA', 'numcode'=>380, 'phonecode'=>39, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'JM', 'name'=>'JAMAICA', 'nicename'=>'Jamaica', 'iso3'=>'JAM', 'numcode'=>388, 'phonecode'=>1876, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'JP', 'name'=>'JAPAN', 'nicename'=>'Japan', 'iso3'=>'JPN', 'numcode'=>392, 'phonecode'=>81, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'JE', 'name'=>'JERSEY', 'nicename'=>'Jersey', 'iso3'=>'JEY', 'numcode'=>832, 'phonecode'=>44, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'JO', 'name'=>'JORDAN', 'nicename'=>'Jordan', 'iso3'=>'JOR', 'numcode'=>400, 'phonecode'=>962, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KZ', 'name'=>'KAZAKHSTAN', 'nicename'=>'Kazakhstan', 'iso3'=>'KAZ', 'numcode'=>398, 'phonecode'=>7, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KE', 'name'=>'KENYA', 'nicename'=>'Kenya', 'iso3'=>'KEN', 'numcode'=>404, 'phonecode'=>254, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KI', 'name'=>'KIRIBATI', 'nicename'=>'Kiribati', 'iso3'=>'KIR', 'numcode'=>296, 'phonecode'=>686, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KP', 'name'=>"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", 'nicename'=>"Korea, Democratic People's Republic of", 'iso3'=>'PRK', 'numcode'=>408, 'phonecode'=>850, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KR', 'name'=>'KOREA, REPUBLIC OF', 'nicename'=>'Korea, Republic of', 'iso3'=>'KOR', 'numcode'=>410, 'phonecode'=>82, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'XK', 'name'=>'KOSOVO', 'nicename'=>'Kosovo', 'iso3'=>'---', 'numcode'=>0, 'phonecode'=>381, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KW', 'name'=>'KUWAIT', 'nicename'=>'Kuwait', 'iso3'=>'KWT', 'numcode'=>414, 'phonecode'=>965, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KG', 'name'=>'KYRGYZSTAN', 'nicename'=>'Kyrgyzstan', 'iso3'=>'KGZ', 'numcode'=>417, 'phonecode'=>996, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LA', 'name'=>"LAO PEOPLE'S DEMOCRATIC REPUBLIC", 'nicename'=>"Lao People's Democratic Republic", 'iso3'=>'LAO', 'numcode'=>418, 'phonecode'=>856, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LV', 'name'=>'LATVIA', 'nicename'=>'Latvia', 'iso3'=>'LVA', 'numcode'=>428, 'phonecode'=>371, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LB', 'name'=>'LEBANON', 'nicename'=>'Lebanon', 'iso3'=>'LBN', 'numcode'=>422, 'phonecode'=>961, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LS', 'name'=>'LESOTHO', 'nicename'=>'Lesotho', 'iso3'=>'LSO', 'numcode'=>426, 'phonecode'=>266, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LR', 'name'=>'LIBERIA', 'nicename'=>'Liberia', 'iso3'=>'LBR', 'numcode'=>430, 'phonecode'=>231, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LY', 'name'=>'LIBYAN ARAB JAMAHIRIYA', 'nicename'=>'Libyan Arab Jamahiriya', 'iso3'=>'LBY', 'numcode'=>434, 'phonecode'=>218, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LI', 'name'=>'LIECHTENSTEIN', 'nicename'=>'Liechtenstein', 'iso3'=>'LIE', 'numcode'=>438, 'phonecode'=>423, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LT', 'name'=>'LITHUANIA', 'nicename'=>'Lithuania', 'iso3'=>'LTU', 'numcode'=>440, 'phonecode'=>370, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LU', 'name'=>'LUXEMBOURG', 'nicename'=>'Luxembourg', 'iso3'=>'LUX', 'numcode'=>442, 'phonecode'=>352, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MO', 'name'=>'MACAO', 'nicename'=>'Macao', 'iso3'=>'MAC', 'numcode'=>446, 'phonecode'=>853, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MK', 'name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'nicename'=>'Macedonia, the Former Yugoslav Republic of', 'iso3'=>'MKD', 'numcode'=>807, 'phonecode'=>389, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MG', 'name'=>'MADAGASCAR', 'nicename'=>'Madagascar', 'iso3'=>'MDG', 'numcode'=>450, 'phonecode'=>261, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MW', 'name'=>'MALAWI', 'nicename'=>'Malawi', 'iso3'=>'MWI', 'numcode'=>454, 'phonecode'=>265, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MY', 'name'=>'MALAYSIA', 'nicename'=>'Malaysia', 'iso3'=>'MYS', 'numcode'=>458, 'phonecode'=>60, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MV', 'name'=>'MALDIVES', 'nicename'=>'Maldives', 'iso3'=>'MDV', 'numcode'=>462, 'phonecode'=>960, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ML', 'name'=>'MALI', 'nicename'=>'Mali', 'iso3'=>'MLI', 'numcode'=>466, 'phonecode'=>223, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MT', 'name'=>'MALTA', 'nicename'=>'Malta', 'iso3'=>'MLT', 'numcode'=>470, 'phonecode'=>356, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MH', 'name'=>'MARSHALL ISLANDS', 'nicename'=>'Marshall Islands', 'iso3'=>'MHL', 'numcode'=>584, 'phonecode'=>692, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MQ', 'name'=>'MARTINIQUE', 'nicename'=>'Martinique', 'iso3'=>'MTQ', 'numcode'=>474, 'phonecode'=>596, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MR', 'name'=>'MAURITANIA', 'nicename'=>'Mauritania', 'iso3'=>'MRT', 'numcode'=>478, 'phonecode'=>222, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MU', 'name'=>'MAURITIUS', 'nicename'=>'Mauritius', 'iso3'=>'MUS', 'numcode'=>480, 'phonecode'=>230, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'YT', 'name'=>'MAYOTTE', 'nicename'=>'Mayotte', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>269, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MX', 'name'=>'MEXICO', 'nicename'=>'Mexico', 'iso3'=>'MEX', 'numcode'=>484, 'phonecode'=>52, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'FM', 'name'=>'MICRONESIA, FEDERATED STATES OF', 'nicename'=>'Micronesia, Federated States of', 'iso3'=>'FSM', 'numcode'=>583, 'phonecode'=>691, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MD', 'name'=>'MOLDOVA, REPUBLIC OF', 'nicename'=>'Moldova, Republic of', 'iso3'=>'MDA', 'numcode'=>498, 'phonecode'=>373, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MC', 'name'=>'MONACO', 'nicename'=>'Monaco', 'iso3'=>'MCO', 'numcode'=>492, 'phonecode'=>377, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MN', 'name'=>'MONGOLIA', 'nicename'=>'Mongolia', 'iso3'=>'MNG', 'numcode'=>496, 'phonecode'=>976, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ME', 'name'=>'MONTENEGRO', 'nicename'=>'Montenegro', 'iso3'=>'MNE', 'numcode'=>499, 'phonecode'=>382, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MS', 'name'=>'MONTSERRAT', 'nicename'=>'Montserrat', 'iso3'=>'MSR', 'numcode'=>500, 'phonecode'=>1664, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MA', 'name'=>'MOROCCO', 'nicename'=>'Morocco', 'iso3'=>'MAR', 'numcode'=>504, 'phonecode'=>212, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MZ', 'name'=>'MOZAMBIQUE', 'nicename'=>'Mozambique', 'iso3'=>'MOZ', 'numcode'=>508, 'phonecode'=>258, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MM', 'name'=>'MYANMAR', 'nicename'=>'Myanmar', 'iso3'=>'MMR', 'numcode'=>104, 'phonecode'=>95, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NA', 'name'=>'NAMIBIA', 'nicename'=>'Namibia', 'iso3'=>'NAM', 'numcode'=>516, 'phonecode'=>264, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NR', 'name'=>'NAURU', 'nicename'=>'Nauru', 'iso3'=>'NRU', 'numcode'=>520, 'phonecode'=>674, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NP', 'name'=>'NEPAL', 'nicename'=>'Nepal', 'iso3'=>'NPL', 'numcode'=>524, 'phonecode'=>977, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NL', 'name'=>'NETHERLANDS', 'nicename'=>'Netherlands', 'iso3'=>'NLD', 'numcode'=>528, 'phonecode'=>31, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AN', 'name'=>'NETHERLANDS ANTILLES', 'nicename'=>'Netherlands Antilles', 'iso3'=>'ANT', 'numcode'=>530, 'phonecode'=>599, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NC', 'name'=>'NEW CALEDONIA', 'nicename'=>'New Caledonia', 'iso3'=>'NCL', 'numcode'=>540, 'phonecode'=>687, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NZ', 'name'=>'NEW ZEALAND', 'nicename'=>'New Zealand', 'iso3'=>'NZL', 'numcode'=>554, 'phonecode'=>64, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NI', 'name'=>'NICARAGUA', 'nicename'=>'Nicaragua', 'iso3'=>'NIC', 'numcode'=>558, 'phonecode'=>505, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NE', 'name'=>'NIGER', 'nicename'=>'Niger', 'iso3'=>'NER', 'numcode'=>562, 'phonecode'=>227, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NG', 'name'=>'NIGERIA', 'nicename'=>'Nigeria', 'iso3'=>'NGA', 'numcode'=>566, 'phonecode'=>234, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NU', 'name'=>'NIUE', 'nicename'=>'Niue', 'iso3'=>'NIU', 'numcode'=>570, 'phonecode'=>683, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NF', 'name'=>'NORFOLK ISLAND', 'nicename'=>'Norfolk Island', 'iso3'=>'NFK', 'numcode'=>574, 'phonecode'=>672, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MP', 'name'=>'NORTHERN MARIANA ISLANDS', 'nicename'=>'Northern Mariana Islands', 'iso3'=>'MNP', 'numcode'=>580, 'phonecode'=>1670, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'NO', 'name'=>'NORWAY', 'nicename'=>'Norway', 'iso3'=>'NOR', 'numcode'=>578, 'phonecode'=>47, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'OM', 'name'=>'OMAN', 'nicename'=>'Oman', 'iso3'=>'OMN', 'numcode'=>512, 'phonecode'=>968, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PK', 'name'=>'PAKISTAN', 'nicename'=>'Pakistan', 'iso3'=>'PAK', 'numcode'=>586, 'phonecode'=>92, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PW', 'name'=>'PALAU', 'nicename'=>'Palau', 'iso3'=>'PLW', 'numcode'=>585, 'phonecode'=>680, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PS', 'name'=>'PALESTINIAN TERRITORY, OCCUPIED', 'nicename'=>'Palestinian Territory, Occupied', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>970, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PA', 'name'=>'PANAMA', 'nicename'=>'Panama', 'iso3'=>'PAN', 'numcode'=>591, 'phonecode'=>507, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PG', 'name'=>'PAPUA NEW GUINEA', 'nicename'=>'Papua New Guinea', 'iso3'=>'PNG', 'numcode'=>598, 'phonecode'=>675, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PY', 'name'=>'PARAGUAY', 'nicename'=>'Paraguay', 'iso3'=>'PRY', 'numcode'=>600, 'phonecode'=>595, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PE', 'name'=>'PERU', 'nicename'=>'Peru', 'iso3'=>'PER', 'numcode'=>604, 'phonecode'=>51, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PH', 'name'=>'PHILIPPINES', 'nicename'=>'Philippines', 'iso3'=>'PHL', 'numcode'=>608, 'phonecode'=>63, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PN', 'name'=>'PITCAIRN', 'nicename'=>'Pitcairn', 'iso3'=>'PCN', 'numcode'=>612, 'phonecode'=>0, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PL', 'name'=>'POLAND', 'nicename'=>'Poland', 'iso3'=>'POL', 'numcode'=>616, 'phonecode'=>48, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PT', 'name'=>'PORTUGAL', 'nicename'=>'Portugal', 'iso3'=>'PRT', 'numcode'=>620, 'phonecode'=>351, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PR', 'name'=>'PUERTO RICO', 'nicename'=>'Puerto Rico', 'iso3'=>'PRI', 'numcode'=>630, 'phonecode'=>1787, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'QA', 'name'=>'QATAR', 'nicename'=>'Qatar', 'iso3'=>'QAT', 'numcode'=>634, 'phonecode'=>974, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'RE', 'name'=>'REUNION', 'nicename'=>'Reunion', 'iso3'=>'REU', 'numcode'=>638, 'phonecode'=>262, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'RO', 'name'=>'ROMANIA', 'nicename'=>'Romania', 'iso3'=>'ROM', 'numcode'=>642, 'phonecode'=>40, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'RU', 'name'=>'RUSSIAN FEDERATION', 'nicename'=>'Russian Federation', 'iso3'=>'RUS', 'numcode'=>643, 'phonecode'=>70, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'RW', 'name'=>'RWANDA', 'nicename'=>'Rwanda', 'iso3'=>'RWA', 'numcode'=>646, 'phonecode'=>250, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'BL', 'name'=>'SAINT BARTHELEMY', 'nicename'=>'Saint Barthelemy', 'iso3'=>'BLM', 'numcode'=>652, 'phonecode'=>590, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SH', 'name'=>'SAINT HELENA', 'nicename'=>'Saint Helena', 'iso3'=>'SHN', 'numcode'=>654, 'phonecode'=>290, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'KN', 'name'=>'SAINT KITTS AND NEVIS', 'nicename'=>'Saint Kitts and Nevis', 'iso3'=>'KNA', 'numcode'=>659, 'phonecode'=>1869, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LC', 'name'=>'SAINT LUCIA', 'nicename'=>'Saint Lucia', 'iso3'=>'LCA', 'numcode'=>662, 'phonecode'=>1758, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'MF', 'name'=>'SAINT MARTIN', 'nicename'=>'Saint Martin', 'iso3'=>'MAF', 'numcode'=>663, 'phonecode'=>590, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'PM', 'name'=>'SAINT PIERRE AND MIQUELON', 'nicename'=>'Saint Pierre and Miquelon', 'iso3'=>'SPM', 'numcode'=>666, 'phonecode'=>508, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'VC', 'name'=>'SAINT VINCENT AND THE GRENADINES', 'nicename'=>'Saint Vincent and the Grenadines', 'iso3'=>'VCT', 'numcode'=>670, 'phonecode'=>1784, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'WS', 'name'=>'SAMOA', 'nicename'=>'Samoa', 'iso3'=>'WSM', 'numcode'=>882, 'phonecode'=>684, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SM', 'name'=>'SAN MARINO', 'nicename'=>'San Marino', 'iso3'=>'SMR', 'numcode'=>674, 'phonecode'=>378, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ST', 'name'=>'SAO TOME AND PRINCIPE', 'nicename'=>'Sao Tome and Principe', 'iso3'=>'STP', 'numcode'=>678, 'phonecode'=>239, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SA', 'name'=>'SAUDI ARABIA', 'nicename'=>'Saudi Arabia', 'iso3'=>'SAU', 'numcode'=>682, 'phonecode'=>966, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SN', 'name'=>'SENEGAL', 'nicename'=>'Senegal', 'iso3'=>'SEN', 'numcode'=>686, 'phonecode'=>221, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'RS', 'name'=>'SERBIA', 'nicename'=>'Serbia', 'iso3'=>'SRB', 'numcode'=>688, 'phonecode'=>381, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CS', 'name'=>'SERBIA AND MONTENEGRO', 'nicename'=>'Serbia and Montenegro', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>381, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SC', 'name'=>'SEYCHELLES', 'nicename'=>'Seychelles', 'iso3'=>'SYC', 'numcode'=>690, 'phonecode'=>248, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SL', 'name'=>'SIERRA LEONE', 'nicename'=>'Sierra Leone', 'iso3'=>'SLE', 'numcode'=>694, 'phonecode'=>232, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SG', 'name'=>'SINGAPORE', 'nicename'=>'Singapore', 'iso3'=>'SGP', 'numcode'=>702, 'phonecode'=>65, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SX', 'name'=>'SINT MAARTEN', 'nicename'=>'Sint Maarten', 'iso3'=>'SXM', 'numcode'=>534, 'phonecode'=>1, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SK', 'name'=>'SLOVAKIA', 'nicename'=>'Slovakia', 'iso3'=>'SVK', 'numcode'=>703, 'phonecode'=>421, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SI', 'name'=>'SLOVENIA', 'nicename'=>'Slovenia', 'iso3'=>'SVN', 'numcode'=>705, 'phonecode'=>386, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SB', 'name'=>'SOLOMON ISLANDS', 'nicename'=>'Solomon Islands', 'iso3'=>'SLB', 'numcode'=>90, 'phonecode'=>677, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SO', 'name'=>'SOMALIA', 'nicename'=>'Somalia', 'iso3'=>'SOM', 'numcode'=>706, 'phonecode'=>252, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ZA', 'name'=>'SOUTH AFRICA', 'nicename'=>'South Africa', 'iso3'=>'ZAF', 'numcode'=>710, 'phonecode'=>27, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GS', 'name'=>'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'nicename'=>'South Georgia and the South Sandwich Islands', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>0, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SS', 'name'=>'SOUTH SUDAN', 'nicename'=>'South Sudan', 'iso3'=>'SSD', 'numcode'=>728, 'phonecode'=>211, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ES', 'name'=>'SPAIN', 'nicename'=>'Spain', 'iso3'=>'ESP', 'numcode'=>724, 'phonecode'=>34, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'LK', 'name'=>'SRI LANKA', 'nicename'=>'Sri Lanka', 'iso3'=>'LKA', 'numcode'=>144, 'phonecode'=>94, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SD', 'name'=>'SUDAN', 'nicename'=>'Sudan', 'iso3'=>'SDN', 'numcode'=>736, 'phonecode'=>249, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SR', 'name'=>'SURINAME', 'nicename'=>'Suriname', 'iso3'=>'SUR', 'numcode'=>740, 'phonecode'=>597, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SJ', 'name'=>'SVALBARD AND JAN MAYEN', 'nicename'=>'Svalbard and Jan Mayen', 'iso3'=>'SJM', 'numcode'=>744, 'phonecode'=>47, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SZ', 'name'=>'SWAZILAND', 'nicename'=>'Swaziland', 'iso3'=>'SWZ', 'numcode'=>748, 'phonecode'=>268, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SE', 'name'=>'SWEDEN', 'nicename'=>'Sweden', 'iso3'=>'SWE', 'numcode'=>752, 'phonecode'=>46, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'CH', 'name'=>'SWITZERLAND', 'nicename'=>'Switzerland', 'iso3'=>'CHE', 'numcode'=>756, 'phonecode'=>41, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'SY', 'name'=>'SYRIAN ARAB REPUBLIC', 'nicename'=>'Syrian Arab Republic', 'iso3'=>'SYR', 'numcode'=>760, 'phonecode'=>963, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TW', 'name'=>'TAIWAN, PROVINCE OF CHINA', 'nicename'=>'Taiwan, Province of China', 'iso3'=>'TWN', 'numcode'=>158, 'phonecode'=>886, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TJ', 'name'=>'TAJIKISTAN', 'nicename'=>'Tajikistan', 'iso3'=>'TJK', 'numcode'=>762, 'phonecode'=>992, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TZ', 'name'=>'TANZANIA, UNITED REPUBLIC OF', 'nicename'=>'Tanzania, United Republic of', 'iso3'=>'TZA', 'numcode'=>834, 'phonecode'=>255, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TH', 'name'=>'THAILAND', 'nicename'=>'Thailand', 'iso3'=>'THA', 'numcode'=>764, 'phonecode'=>66, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TL', 'name'=>'TIMOR-LESTE', 'nicename'=>'Timor-Leste', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>670, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TG', 'name'=>'TOGO', 'nicename'=>'Togo', 'iso3'=>'TGO', 'numcode'=>768, 'phonecode'=>228, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TK', 'name'=>'TOKELAU', 'nicename'=>'Tokelau', 'iso3'=>'TKL', 'numcode'=>772, 'phonecode'=>690, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TO', 'name'=>'TONGA', 'nicename'=>'Tonga', 'iso3'=>'TON', 'numcode'=>776, 'phonecode'=>676, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TT', 'name'=>'TRINIDAD AND TOBAGO', 'nicename'=>'Trinidad and Tobago', 'iso3'=>'TTO', 'numcode'=>780, 'phonecode'=>1868, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TN', 'name'=>'TUNISIA', 'nicename'=>'Tunisia', 'iso3'=>'TUN', 'numcode'=>788, 'phonecode'=>216, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TR', 'name'=>'TURKEY', 'nicename'=>'Turkey', 'iso3'=>'TUR', 'numcode'=>792, 'phonecode'=>90, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TM', 'name'=>'TURKMENISTAN', 'nicename'=>'Turkmenistan', 'iso3'=>'TKM', 'numcode'=>795, 'phonecode'=>7370, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TC', 'name'=>'TURKS AND CAICOS ISLANDS', 'nicename'=>'Turks and Caicos Islands', 'iso3'=>'TCA', 'numcode'=>796, 'phonecode'=>1649, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'TV', 'name'=>'TUVALU', 'nicename'=>'Tuvalu', 'iso3'=>'TUV', 'numcode'=>798, 'phonecode'=>688, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'UG', 'name'=>'UGANDA', 'nicename'=>'Uganda', 'iso3'=>'UGA', 'numcode'=>800, 'phonecode'=>256, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'UA', 'name'=>'UKRAINE', 'nicename'=>'Ukraine', 'iso3'=>'UKR', 'numcode'=>804, 'phonecode'=>380, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'AE', 'name'=>'UNITED ARAB EMIRATES', 'nicename'=>'United Arab Emirates', 'iso3'=>'ARE', 'numcode'=>784, 'phonecode'=>971, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'GB', 'name'=>'UNITED KINGDOM', 'nicename'=>'United Kingdom', 'iso3'=>'GBR', 'numcode'=>826, 'phonecode'=>44, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'US', 'name'=>'UNITED STATES', 'nicename'=>'United States', 'iso3'=>'USA', 'numcode'=>840, 'phonecode'=>1, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'UM', 'name'=>'UNITED STATES MINOR OUTLYING ISLANDS', 'nicename'=>'United States Minor Outlying Islands', 'iso3'=>NULL, 'numcode'=>NULL, 'phonecode'=>1, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'UY', 'name'=>'URUGUAY', 'nicename'=>'Uruguay', 'iso3'=>'URY', 'numcode'=>858, 'phonecode'=>598, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'UZ', 'name'=>'UZBEKISTAN', 'nicename'=>'Uzbekistan', 'iso3'=>'UZB', 'numcode'=>860, 'phonecode'=>998, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'VU', 'name'=>'VANUATU', 'nicename'=>'Vanuatu', 'iso3'=>'VUT', 'numcode'=>548, 'phonecode'=>678, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'VE', 'name'=>'VENEZUELA', 'nicename'=>'Venezuela', 'iso3'=>'VEN', 'numcode'=>862, 'phonecode'=>58, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'VN', 'name'=>'VIET NAM', 'nicename'=>'Viet Nam', 'iso3'=>'VNM', 'numcode'=>704, 'phonecode'=>84, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'VG', 'name'=>'VIRGIN ISLANDS, BRITISH', 'nicename'=>'Virgin Islands, British', 'iso3'=>'VGB', 'numcode'=>92, 'phonecode'=>1284, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'VI', 'name'=>'VIRGIN ISLANDS, U.S.', 'nicename'=>'Virgin Islands, U.s.', 'iso3'=>'VIR', 'numcode'=>850, 'phonecode'=>1340, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'WF', 'name'=>'WALLIS AND FUTUNA', 'nicename'=>'Wallis and Futuna', 'iso3'=>'WLF', 'numcode'=>876, 'phonecode'=>681, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'EH', 'name'=>'WESTERN SAHARA', 'nicename'=>'Western Sahara', 'iso3'=>'ESH', 'numcode'=>732, 'phonecode'=>212, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'YE', 'name'=>'YEMEN', 'nicename'=>'Yemen', 'iso3'=>'YEM', 'numcode'=>887, 'phonecode'=>967, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ZM', 'name'=>'ZAMBIA', 'nicename'=>'Zambia', 'iso3'=>'ZMB', 'numcode'=>894, 'phonecode'=>260, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);
		Country::firstOrCreate( ['iso'=>'ZW', 'name'=>'ZIMBABWE', 'nicename'=>'Zimbabwe', 'iso3'=>'ZWE', 'numcode'=>716, 'phonecode'=>263, 'updated_at'=>date('Y-m-d H:i:s'), 'created_at'=>date('Y-m-d H:i:s')]);		
		
    }
}
